### ISSUE TITLE
Doctor info

### ISSUE THREAD

**Issue by Pauloper1** [Pranav122002/Medi-Share#13]
Need to add:
1. specialization
2. Hositpal name and location
3. Fees
4. Doctor availability
5. rating
6. Phone

**Comment by Pranav122002** [comment]
Need to add : 
1) More Doctor details
2) Doctors profile page
3) Confirm / Reject option for appointment

**Comment by Pranav122002** [comment]
Need to add : 

1) More Doctor details
2) Doctors profile page
3) Confirm / Reject option for appointments
4) User must book appointment with credits
